apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-1i8w67
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1i8w67
  namespace: my-nginx-1i8w67
  labels:
    name: nginx-1i8w67
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-1i8w67
  template:
    metadata:
      namespace: my-nginx-1i8w67
      labels:
        name: nginx-1i8w67
    spec:
      containers:
      - name: nginx-1i8w67
        image: nginx
        ports:
        - containerPort: 80

